### ISSUE TITLE
Fail to bind music file on macOS

### ISSUE THREAD

**Issue by johnthagen** [johnthagen/rust-belt#175]
```
$ cargo run
...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Unrecognized audio format"', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: std::panicking::try::do_call
             at libstd/panicking.rs:325
   7: core::ptr::drop_in_place
             at libcore/panicking.rs:77
   8: core::ptr::swap_nonoverlapping_bytes
             at /Users/travis/build/rust-lang/rust/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at /Users/travis/build/rust-lang/rust/src/libcore/result.rs:782
  10: music::bind_music_file
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/piston-music-0.24.0/src/lib.rs:87
  11: rust_belt::menu::bind_sound_files
             at src/menu.rs:62
  12: rust_belt::menu::run::{{closure}}
             at src/menu.rs:179
  13: music::start_context
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/piston-music-0.24.0/src/lib.rs:74
  14: music::start
             at /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/piston-music-0.24.0/src/lib.rs:53
  15: rust_belt::menu::run
             at src/menu.rs:178
  16: rust_belt::main
             at src/main.rs:40
  17: std::rt::lang_start::{{closure}}
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  18: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  19: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:105
  20: <std::sync::mutex::Mutex<T>>::new
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  21: std::rt::lang_start
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  22: rust_belt::main

Process finished with exit code 101
```

**Comment by johnthagen** [comment]
Fixed in 409f07c8c90c763682cfd98ac731c907ccadf355.
